server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/books
    username: postgres
    password: postgres
    hikari:
      schema: books_schema
      connection-timeout: 1000

